title:             Dev Blog
email:             quinndonnelly22@gmail.com
description:       With Quintin Donnelly
author:            Quinn-Donnelly
baseurl:           "/QuinnGetsSassy"
url:               "http://quinn-donnelly.github.io"

# Social Profiles
twitter_username:  QuinnDonnelly_
github_username:   Quinn-Donnelly
facebook_username: quinndonnelly22

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
